# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aed78b7972c1027113f129e7f52a826e1ce2981751ca38c985691151ef93c36c6aa8584e5924522c9f8c3155e96218ead300c970b1030c29337493dcf99f4125

test:
  secret_key_base: 5cedf2334e9466fdb8291a6f13c0533673f7a21f646c192ebb86a23f02396c0a1083495207ea5ab25ba71cd2847f7a93da600cb2d9197b771e464f09c28cb12d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
